//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminal.ADOApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABDEntities : DbContext
    {
        public ABDEntities()
            : base("name=ABDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<academicApplicant> academicApplicant { get; set; }
        public virtual DbSet<academics> academics { get; set; }
        public virtual DbSet<acceptance> acceptance { get; set; }
        public virtual DbSet<applicants> applicants { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
